// resources/js/pages/Admin/Orders/Show.vue
<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';

type Item = {
    id: number;
    product_name: string;
    product_sku: string | null;
    quantity: number;
    unit_price: number;
    total_amount: number;
};
type Payment = {
    id: number;
    amount: number;
    gateway: string | null;
    status: string;
    authority: string | null;
    transaction_id: string | null;
    reference_number: string | null;
    paid_at: string | null;
};
type Order = {
    id: number;
    order_number: string;
    status: string;
    payment_status: string;
    subtotal: number;
    discount_amount: number;
    shipping_amount: number;
    total_amount: number;
    currency: string;
    recipient_name: string | null;
    recipient_phone: string | null;
    province: string | null;
    city: string | null;
    shipping_address: string | null;
    postal_code: string | null;
    customer_note: string | null;
    admin_note: string | null;
    created_at: string;
    user: { name: string | null; phone: string | null } | null;
    items: Item[];
    payments: Payment[];
};

const props = defineProps<{ order: Order; success?: string; error?: string }>();
const formatAmount = (amount: number) =>
    new Intl.NumberFormat('fa-IR').format(amount);
const statusLabel = (value: string) =>
    ({
        pending: 'در انتظار',
        paid: 'پرداخت شده',
        processing: 'در حال پردازش',
        shipped: 'ارسال شده',
        delivered: 'تحویل شده',
        cancelled: 'لغو شده',
    })[value] || value;
const paymentLabel = (value: string) =>
    ({
        pending: 'در انتظار',
        paid: 'موفق',
        failed: 'ناموفق',
        refunded: 'برگشت خورده',
    })[value] || value;
const nextStatus = (value: string) =>
    ({
        pending: 'paid',
        paid: 'processing',
        processing: 'shipped',
        shipped: 'delivered',
    })[value] || null;
const nextStatusLabel = (value: string) =>
    ({
        paid: 'تأیید پرداخت',
        processing: 'شروع پردازش',
        shipped: 'ثبت ارسال',
        delivered: 'ثبت تحویل',
    })[value] || value;
const changeStatus = (status: string) =>
    router.post(`/admin/orders/${props.order.id}/status`, { status });
</script>

<template>
    <Head :title="`سفارش ${order.order_number}`" />
    <div
        dir="rtl"
        class="min-h-screen bg-dh-50 px-4 py-8 text-dh-900 sm:px-6 lg:px-8"
    >
        <div class="mx-auto max-w-5xl">
            <div class="mb-8 flex items-center justify-between gap-4">
                <div>
                    <p class="text-sm text-dh-muted">HealthStore / سفارش‌ها</p>
                    <h1 class="text-2xl font-bold">{{ order.order_number }}</h1>
                </div>
                <Link
                    href="/admin/orders"
                    class="rounded-lg border border-dh-200 bg-white px-4 py-2 text-sm hover:bg-dh-50"
                    >بازگشت</Link
                >
            </div>
            <div
                v-if="success"
                class="mb-4 rounded-lg bg-green-50 p-3 text-sm text-green-700"
            >
                {{ success }}
            </div>
            <div
                v-if="error"
                class="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700"
            >
                {{ error }}
            </div>

            <div class="grid gap-6 lg:grid-cols-3">
                <section
                    class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-dh-100 lg:col-span-2"
                >
                    <div class="mb-5 flex items-center justify-between">
                        <h2 class="font-bold">وضعیت سفارش</h2>
                        <span class="rounded-full bg-dh-50 px-3 py-1 text-sm">{{
                            statusLabel(order.status)
                        }}</span>
                    </div>
                    <div
                        v-if="nextStatus(order.status)"
                        class="flex flex-wrap gap-2"
                    >
                        <button
                            type="button"
                            class="rounded-lg bg-dh-700 px-4 py-2 text-sm text-white hover:bg-dh-800"
                            @click="changeStatus(nextStatus(order.status)!)"
                        >
                            {{ nextStatusLabel(nextStatus(order.status)!) }}
                        </button>
                    </div>
                    <p v-else class="text-sm text-dh-muted">
                        برای این وضعیت، عملیات بعدی تعریف نشده است.
                    </p>
                </section>
                <section
                    class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-dh-100"
                >
                    <h2 class="mb-4 font-bold">مشتری</h2>
                    <p>{{ order.user?.name || order.recipient_name || '—' }}</p>
                    <p class="mt-1 text-sm text-dh-muted">
                        {{ order.user?.phone || order.recipient_phone || '—' }}
                    </p>
                </section>
            </div>

            <section
                class="mt-6 rounded-xl bg-white p-5 shadow-sm ring-1 ring-dh-100"
            >
                <h2 class="mb-4 font-bold">اقلام سفارش</h2>
                <div class="overflow-x-auto">
                    <table class="min-w-full text-right text-sm">
                        <thead class="border-b text-dh-muted">
                            <tr>
                                <th class="px-2 py-3">محصول</th>
                                <th class="px-2 py-3">تعداد</th>
                                <th class="px-2 py-3">قیمت واحد</th>
                                <th class="px-2 py-3">جمع</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y">
                            <tr v-for="item in order.items" :key="item.id">
                                <td class="px-2 py-3">
                                    <div class="font-medium">
                                        {{ item.product_name }}
                                    </div>
                                    <div class="text-xs text-dh-muted">
                                        {{ item.product_sku || '—' }}
                                    </div>
                                </td>
                                <td class="px-2 py-3">{{ item.quantity }}</td>
                                <td class="px-2 py-3">
                                    {{ formatAmount(Number(item.unit_price)) }}
                                </td>
                                <td class="px-2 py-3 font-medium">
                                    {{
                                        formatAmount(Number(item.total_amount))
                                    }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="mt-5 border-t pt-4 text-sm">
                    <div class="flex justify-between">
                        <span>جمع کالاها</span
                        ><span>{{ formatAmount(Number(order.subtotal)) }}</span>
                    </div>
                    <div class="mt-2 flex justify-between">
                        <span>تخفیف</span
                        ><span>{{
                            formatAmount(Number(order.discount_amount))
                        }}</span>
                    </div>
                    <div class="mt-2 flex justify-between">
                        <span>ارسال</span
                        ><span>{{
                            formatAmount(Number(order.shipping_amount))
                        }}</span>
                    </div>
                    <div class="mt-3 flex justify-between text-base font-bold">
                        <span>مبلغ نهایی</span
                        ><span
                            >{{
                                formatAmount(Number(order.total_amount))
                            }}
                            ریال</span
                        >
                    </div>
                </div>
            </section>

            <div class="mt-6 grid gap-6 lg:grid-cols-2">
                <section
                    class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-dh-100"
                >
                    <h2 class="mb-4 font-bold">آدرس ارسال</h2>
                    <p>{{ order.recipient_name || '—' }}</p>
                    <p class="mt-1 text-sm">
                        {{ order.recipient_phone || '—' }}
                    </p>
                    <p class="mt-3 text-sm text-dh-700">
                        {{ order.province || '' }} {{ order.city || '' }}
                    </p>
                    <p class="mt-1 text-sm text-dh-700">
                        {{ order.shipping_address || '—' }}
                    </p>
                    <p class="mt-1 text-sm text-dh-muted">
                        کد پستی: {{ order.postal_code || '—' }}
                    </p>
                </section>
                <section
                    class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-dh-100"
                >
                    <h2 class="mb-4 font-bold">پرداخت‌ها</h2>
                    <div
                        v-for="payment in order.payments"
                        :key="payment.id"
                        class="border-b py-3 last:border-0"
                    >
                        <div class="flex justify-between">
                            <span>{{ payment.gateway || 'درگاه' }}</span
                            ><span>{{ paymentLabel(payment.status) }}</span>
                        </div>
                        <div class="mt-1 text-sm text-dh-muted">
                            {{ formatAmount(Number(payment.amount)) }} ریال
                        </div>
                        <div class="mt-1 text-xs text-dh-muted">
                            تراکنش: {{ payment.transaction_id || '—' }}
                        </div>
                    </div>
                    <p
                        v-if="order.payments.length === 0"
                        class="text-sm text-dh-muted"
                    >
                        پرداختی ثبت نشده است.
                    </p>
                </section>
            </div>
        </div>
    </div>
</template>

// resources/js/pages/Order/Show.tsx
import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';

type OrderItem = {
    id: number;
    product_id: number | null;
    product_name: string;
    product_sku: string | null;
    quantity: number;
    unit_price: string;
    discount_amount: string;
    total_amount: string;
};

type Payment = {
    id: number;
    amount: string;
    gateway: string | null;
    status: string;
    authority: string | null;
    transaction_id: string | null;
    reference_number: string | null;
    paid_at: string | null;
};

type Order = {
    id: number;
    order_number: string;
    user_id: number | null;
    customer_type: string;
    status: string;
    payment_status: string;
    subtotal: string;
    discount_amount: string;
    shipping_amount: string;
    total_amount: string;
    currency: string;
    recipient_name: string | null;
    recipient_phone: string | null;
    province: string | null;
    city: string | null;
    shipping_address: string | null;
    postal_code: string | null;
    customer_note: string | null;
    admin_note: string | null;
    confirmed_at: string | null;
    paid_at: string | null;
    shipped_at: string | null;
    delivered_at: string | null;
    cancelled_at: string | null;
    created_at: string;
    updated_at: string;
    items: OrderItem[];
    payments: Payment[];
};

type Props = {
    order: Order;
    success?: string | null;
    error?: string | null;
    info?: string | null;
};

function orderStatusLabel(status: string): string {
    switch (status) {
        case 'pending':
            return 'در انتظار پرداخت';

        case 'paid':
            return 'پرداخت شده';

        case 'processing':
            return 'در حال پردازش';

        case 'shipped':
            return 'ارسال شده';

        case 'delivered':
            return 'تحویل شده';

        case 'cancelled':
            return 'لغو شده';

        default:
            return status;
    }
}

function paymentStatusLabel(status: string): string {
    switch (status) {
        case 'pending':
            return 'در انتظار پرداخت';

        case 'paid':
            return 'پرداخت موفق';

        case 'failed':
            return 'پرداخت ناموفق';

        case 'cancelled':
            return 'لغو شده';

        default:
            return status;
    }
}

function formatAmount(
    amount: string,
    currency: string
): string {
    const numericAmount = Number(amount);

    if (Number.isNaN(numericAmount)) {
        return `${amount} ${currency}`;
    }

    return `${numericAmount.toLocaleString('fa-IR')} ${currency}`;
}

function formatDate(
    date: string | null
): string {
    if (!date) {
        return '—';
    }

    return new Date(date).toLocaleString('fa-IR');
}

export default function Show({
    order,
    success,
    error,
    info,
}: Props) {
    const [isCancelling, setIsCancelling] =
        useState(false);

    const canCancel =
        order.status === 'pending' &&
        order.payment_status !== 'paid';

    function cancelOrder() {
        if (!canCancel || isCancelling) {
            return;
        }

        const confirmed = window.confirm(
            'آیا از لغو این سفارش مطمئن هستید؟'
        );

        if (!confirmed) {
            return;
        }

        setIsCancelling(true);

        router.post(
            `/orders/${order.order_number}/cancel`,
            {},
            {
                onFinish: () => {
                    setIsCancelling(false);
                },
            }
        );
    }

    return (
        <>
            <Head
                title={`سفارش ${order.order_number}`}
            />

            <div>
                <div>
                    <Link href="/account/orders">
                        بازگشت به سفارش‌های من
                    </Link>
                </div>

                <h1>
                    جزئیات سفارش
                </h1>

                {success && (
                    <div>
                        {success}
                    </div>
                )}

                {error && (
                    <div>
                        {error}
                    </div>
                )}

                {info && (
                    <div>
                        {info}
                    </div>
                )}

                <section>
                    <h2>
                        اطلاعات سفارش
                    </h2>

                    <p>
                        شماره سفارش:{' '}
                        {order.order_number}
                    </p>

                    <p>
                        تاریخ ثبت:{' '}
                        {formatDate(
                            order.created_at
                        )}
                    </p>

                    <p>
                        وضعیت سفارش:{' '}
                        {orderStatusLabel(
                            order.status
                        )}
                    </p>

                    <p>
                        وضعیت پرداخت:{' '}
                        {paymentStatusLabel(
                            order.payment_status
                        )}
                    </p>

                    {order.confirmed_at && (
                        <p>
                            تاریخ تأیید:{' '}
                            {formatDate(
                                order.confirmed_at
                            )}
                        </p>
                    )}

                    {order.paid_at && (
                        <p>
                            تاریخ پرداخت:{' '}
                            {formatDate(
                                order.paid_at
                            )}
                        </p>
                    )}

                    {order.shipped_at && (
                        <p>
                            تاریخ ارسال:{' '}
                            {formatDate(
                                order.shipped_at
                            )}
                        </p>
                    )}

                    {order.delivered_at && (
                        <p>
                            تاریخ تحویل:{' '}
                            {formatDate(
                                order.delivered_at
                            )}
                        </p>
                    )}

                    {order.cancelled_at && (
                        <p>
                            تاریخ لغو:{' '}
                            {formatDate(
                                order.cancelled_at
                            )}
                        </p>
                    )}
                </section>

                <section>
                    <h2>
                        اقلام سفارش
                    </h2>

                    {order.items.length === 0 ? (
                        <p>
                            آیتمی برای این سفارش ثبت نشده است.
                        </p>
                    ) : (
                        <div>
                            {order.items.map(
                                (item) => (
                                    <div
                                        key={item.id}
                                    >
                                        <h3>
                                            {
                                                item.product_name
                                            }
                                        </h3>

                                        {item.product_sku && (
                                            <p>
                                                کد کالا:{' '}
                                                {
                                                    item.product_sku
                                                }
                                            </p>
                                        )}

                                        <p>
                                            تعداد:{' '}
                                            {
                                                item.quantity
                                            }
                                        </p>

                                        <p>
                                            قیمت واحد:{' '}
                                            {formatAmount(
                                                item.unit_price,
                                                order.currency
                                            )}
                                        </p>

                                        <p>
                                            مبلغ کل:{' '}
                                            {formatAmount(
                                                item.total_amount,
                                                order.currency
                                            )}
                                        </p>

                                        {Number(
                                            item.discount_amount
                                        ) > 0 && (
                                            <p>
                                                تخفیف:{' '}
                                                {formatAmount(
                                                    item.discount_amount,
                                                    order.currency
                                                )}
                                            </p>
                                        )}
                                    </div>
                                )
                            )}
                        </div>
                    )}
                </section>

                <section>
                    <h2>
                        اطلاعات گیرنده و ارسال
                    </h2>

                    <p>
                        نام گیرنده:{' '}
                        {order.recipient_name ||
                            '—'}
                    </p>

                    <p>
                        شماره تماس:{' '}
                        {order.recipient_phone ||
                            '—'}
                    </p>

                    <p>
                        استان:{' '}
                        {order.province || '—'}
                    </p>

                    <p>
                        شهر:{' '}
                        {order.city || '—'}
                    </p>

                    <p>
                        آدرس:{' '}
                        {order.shipping_address ||
                            '—'}
                    </p>

                    <p>
                        کد پستی:{' '}
                        {order.postal_code || '—'}
                    </p>

                    {order.customer_note && (
                        <p>
                            توضیحات مشتری:{' '}
                            {order.customer_note}
                        </p>
                    )}
                </section>

                <section>
                    <h2>
                        خلاصه مبلغ
                    </h2>

                    <p>
                        مبلغ کالاها:{' '}
                        {formatAmount(
                            order.subtotal,
                            order.currency
                        )}
                    </p>

                    <p>
                        تخفیف:{' '}
                        {formatAmount(
                            order.discount_amount,
                            order.currency
                        )}
                    </p>

                    <p>
                        هزینه ارسال:{' '}
                        {formatAmount(
                            order.shipping_amount,
                            order.currency
                        )}
                    </p>

                    <p>
                        مبلغ نهایی:{' '}
                        <strong>
                            {formatAmount(
                                order.total_amount,
                                order.currency
                            )}
                        </strong>
                    </p>
                </section>

                {order.payments.length > 0 && (
                    <section>
                        <h2>
                            پرداخت‌ها
                        </h2>

                        {order.payments.map(
                            (payment) => (
                                <div
                                    key={payment.id}
                                >
                                    <p>
                                        مبلغ پرداخت:{' '}
                                        {formatAmount(
                                            payment.amount,
                                            order.currency
                                        )}
                                    </p>

                                    <p>
                                        وضعیت:{' '}
                                        {paymentStatusLabel(
                                            payment.status
                                        )}
                                    </p>

                                    {payment.gateway && (
                                        <p>
                                            درگاه:{' '}
                                            {
                                                payment.gateway
                                            }
                                        </p>
                                    )}

                                    {payment.reference_number && (
                                        <p>
                                            شماره مرجع:{' '}
                                            {
                                                payment.reference_number
                                            }
                                        </p>
                                    )}

                                    {payment.transaction_id && (
                                        <p>
                                            شناسه تراکنش:{' '}
                                            {
                                                payment.transaction_id
                                            }
                                        </p>
                                    )}

                                    {payment.paid_at && (
                                        <p>
                                            تاریخ پرداخت:{' '}
                                            {formatDate(
                                                payment.paid_at
                                            )}
                                        </p>
                                    )}
                                </div>
                            )
                        )}
                    </section>
                )}

                {canCancel && (
                    <section>
                        <button
                            type="button"
                            onClick={cancelOrder}
                            disabled={isCancelling}
                        >
                            {isCancelling
                                ? 'در حال لغو سفارش...'
                                : 'لغو سفارش'}
                        </button>
                    </section>
                )}
            </div>
        </>
    );
}
